name: joinable_env
channels:
  - pytorch
  - rusty1s
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch=1.8
  - torchvision=0.9.1
  - pytorch-lightning=1.3.7
  - torchmetrics=0.4.0
  - matplotlib
  - tqdm
  - pytorch-geometric=1.7.2
  - networkx
  - scipy
  - igl
  - meshplot
  - pip:
    - pysdf
    - trimesh[easy]